Console.WriteLine($"Введите первую цифру (пол,век рождения)");
int a = Convert.ToInt16(Console.ReadLine());
Console.WriteLine($"Введите вторую цифру (первая из двух последних цифр года рождения)");
int b = Convert.ToInt16(Console.ReadLine());
Console.WriteLine($"Введите третью цифру (вторая из двух последних цифр года рождения)");
int c = Convert.ToInt16(Console.ReadLine());
Console.WriteLine($"Введите четвёртую цифру (первая из двух последних цифр месяца рождения)");
int d = Convert.ToInt16(Console.ReadLine());
Console.WriteLine($"Введите пятую цифру (вторую из двух последних цифр месяца рождения)");
int e = Convert.ToInt16(Console.ReadLine());
Console.WriteLine($"Введите шестую цифру (первую из двух последних цифр дня рождения)");
int f = Convert.ToInt16(Console.ReadLine());
Console.WriteLine($"Введите седьмую цифру (вторую из двух последних цифр дня рождения)");
int g = Convert.ToInt16(Console.ReadLine());
Console.WriteLine($"Введите восьмую цифру (первую цифру кода города проживания от 01-52)");
int h = Convert.ToInt16(Console.ReadLine());
Console.WriteLine($"Введите девятую цифру (вторую цифру кода города проживания от 01-52)");
int i = Convert.ToInt16(Console.ReadLine());
Console.WriteLine($"Введите десятую цифру (первую цифру номера заказа (3 любые цифры)");
int j = Convert.ToInt16(Console.ReadLine());
Console.WriteLine($"Введите одиннадцатую цифру (вторую цифру номера заказа (3 любые цифры)");
int k = Convert.ToInt16(Console.ReadLine());
Console.WriteLine($"Введите двенадцатую цифру (третью цифру номера заказа (3 любые цифры)");
int l = Convert.ToInt16(Console.ReadLine());
int sum = (1*a)+(2*b)+(3*c)+(4*d)+(5*e)+(6*f)+(7*g)+(8*h)+(9*i)+(10*j)+(11*k)+(12*l);
Console.WriteLine(sum);
double res = sum%11;
Console.WriteLine(res);